encoding: utf-8

# SEO相关信息
title: xh511 Blog
description: xh511的个人博客
keywords: Blog,Java,Html,JavaScript
author: xh
footerText: ''

# GitHub.Pages访问站点路径
githubUrl: 'xh511.github.io'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: ''
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
#tucaoUrl: https://support.qq.com/product/86335

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
#  - title: 留言
#    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 文章底部广告
# 位置 _includes/adsense.html
#adsense: true

# 自定义插件
# plugin-mta-stats
# 腾讯移动分析(https://mta.qq.com)，如果需要请申请自己的，不需要的话 use 请设置为 false
# plugin-baidu-push
# 百度收录自动推送，不需要的话 use 请设置为 false
# plugin-click-effect
# 页面点击，出现核心主义价值观
# plugin-mathjax
# 数学公式支持，比较影响加载速度，请设置为 false
customPlugins:
  - use: false
    file: 'plugin-mta-stats.html'
    sid: 500581966
    cid: 500581972
  - use: false
    file: 'plugin-baidu-push.html'
  - use: true
    file: 'plugin-click-effect.html'
  - use: false
    file: 'plugin-mathjax.html'

# 友情链接
links:
  - title: TMaize的个人博客
    url: http://blog.tmaize.net
#  - title: 文科中的技术宅
#    url: https://www.townwang.com

